### ISSUE TITLE
Make it possible to override image, registry and repo for Grafana and Ruler in values file.

### ISSUE THREAD

**Issue by Jaypers** [grafana/meta-monitoring-chart#175]
While this is possible for subcharts/dependencies it isn't possible for Grafana or the Ruler in the meta-monitoring values file.
This assists with consuming from docker proxies with tools like Nexus.
E.g.:
```
    image:
      registry: nexus.example.com
      repository: grafana/grafana
      tag: 11.3.1
```
or
```
    image: nexus.example.com/grafana/grafana:11.3.1
```
